spring:
  datasource:
    url: jdbc:h2:mem:splitwisedb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:default_dev_secret_key_do_not_use_in_production}
  expiration: 86400000 # 24 hours

gemini:
  endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
  apiKey: ${GEMINI_API_KEY}

prompts:
  extractItems: |
    Extract all item names and prices from this bill, use upto 2 decimal precision for prices and give them in following json format [{"name": "item1", "price": <price in float>}]